/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    projects: Project;
    media: Media;
    profiles: Profile;
    users: User;
  };
  globals: {};
}
export interface Page {
  id: string;
  title: string;
  richText?: {
    [k: string]: unknown;
  }[];
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Project {
  id: string;
  images?: {
    image?: string | Media;
    id?: string;
  }[];
  featuredImage?: string | Media;
  title: string;
  role: string;
  startDate?: string;
  endDate?: string;
  technologiesUsed: {
    technology: string;
    id?: string;
  }[];
  description: {
    [k: string]: unknown;
  }[];
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Profile {
  id: string;
  name: string;
  location?: string;
  title?: string;
  aboutMe?: {
    [k: string]: unknown;
  }[];
  profileImage?: string | Media;
  socialLinks?: {
    github?: string;
    linkedin?: string;
    email?: string;
    twitter?: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
