name: Code formatting
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx}
          prettier_plugins:
            - "prettier-plugin-tailwindcss"
          only_changed: True

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5