name: Code formatting
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.9.0'

      - name: Format code
        run: |
          npm i -g pnpm
          pnpm i
          pnpm run format

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5